### ISSUE TITLE
Lsp functionality not working inside lua plugins

### ISSUE THREAD

**Issue by akinsho** [folke/lua-dev.nvim#21] opened 2021-07-31 11:14 UTC
Hi @folke,

I've been using this plugin and quite enjoying it for developing my plugins. Recently though, i.e. the last good commit that is working for me cf3b028, I have not been getting diagnostics or other lsp functionality inside my lua plugins. I see some changes around a workspace plugin in 681c0fc, which is the commit that broke things for me, though I've not dug in enough to know what happened. My config for the plugins is
```lua
lspconfig = {
        settings = {
          Lua = {
            diagnostics = {
              globals = {
                'vim',
                'describe',
                'it',
                'before_each',
                'after_each',
                'pending',
                'teardown',
                'packer_plugins',
              },
            },
            completion = { keywordSnippet = 'Replace', callSnippet = 'Replace' },
          },
        },
      }
```

**Comment by folke** [comment] 2021-08-03 19:45
I probably broke something related to a new plugin I'm making. I've been traveling for the last two weeks, but I'm planning to do some maintenance on all my plugins tomorrow.

**Comment by folke** [comment] 2021-08-05 07:10
@akinsho I just tested with the latest version without the workspace stuff and everything still seems to work for me as expected.

Can you show the me the exact code you use to set it up?

**Comment by akinsho** [comment] 2021-08-05 09:12
@folke so my setup is
```lua
as.lsp.servers = {
  lua = function()
    return require('lua-dev').setup {
      lspconfig = {
        settings = {
          Lua = {
            diagnostics = {
              globals = {
                'vim',
                'describe',
                'it',
                'before_each',
                'after_each',
                'pending',
                'teardown',
                'packer_plugins',
              },
            },
            completion = { keywordSnippet = 'Replace', callSnippet = 'Replace' },
          },
        },
      },
    }
  end,
}

-- Later on the servers are initialised
  local lspinstall = require 'lspinstall'
  local lspconfig = require 'lspconfig'

  lspinstall.setup()
  local installed = lspinstall.installed_servers()
  local status_capabilities = require('lsp-status').capabilities
  for _, server in pairs(installed) do
    local config = as.lsp.servers[server] and as.lsp.servers[server]() or {}
    config.flags = { debounce_text_changes = 150 }
    config.on_attach = as.lsp.on_attach
    config.capabilities = vim.lsp.protocol.make_client_capabilities()
    config.capabilities.textDocument.completion.completionItem.snippetSupport = true
    config.capabilities.textDocument.completion.completionItem.resolveSupport = {
      properties = {
        'documentation',
        'detail',
        'additionalTextEdits',
      },
    }
    -- as.deep_merge is similar to vim.tbl_deep_extend
    config.capabilities = as.deep_merge(status_capabilities, config.capabilities)
    lspconfig[server].setup(config)
  end
```
I've included the whole setup just in case there is something relevant here, also note that I install my servers using lspinstall

**Comment by folke** [comment] 2021-08-05 09:22
What does `LspInfo` say? Is sumneko properly connected?

Could you open a new lua file, add in the below and execute it with `:luafile %`?

```lua
  local ret = {}
  for _, client in pairs(vim.lsp.get_active_clients()) do
    ret[client.name] = { root_dir = client.config.root_dir, settings = client.config.settings }
  end
print(vim.inspect(ret))
```

**Comment by akinsho** [comment] 2021-08-05 09:42
I checked at the time and the lsp seemed to be attached since I didn't notice for a while since I was still getting completions. I'm currently on my mac which I don't develop lua stuff, just tried this out on that after adding in lua-dev and the lsp isn't attaching and result is an empty table but it's not the best test since this isn't my normal lua dev environment. FWIW it does connect correctly inside my dotfiles repo though. Seems like it's only working inside directories in my runtime path.

If this isn't helpful Ill redo this test on my dev machine when I get back to it tomorrow

**Comment by muniter** [comment] 2021-08-06 00:22
Can't confirm having the same issue, going back to commit https://github.com/folke/lua-dev.nvim/commit/5e6caa92b83a07a516d481593344bed1e6eebd6a worked for me. The behavior was I got no diagnostics on plugin files, but It was working on my `init.lua`. Also disabling `vimruntime` in master also makes diagnostics work again.

**Comment by folke** [comment] 2021-08-06 06:46
If you say you get no diagnostics, what do you mean exactly by that?

Does auto completion work?

If I understand correctly, something is broken when you are in a project like `~/projects/foo/lua/bar/init.lua`? And you `require` files there from a vim plugin?

**Comment by folke** [comment] 2021-08-06 06:59
Note to self: diff between last working version and main: https://github.com/folke/lua-dev.nvim/compare/cf3b028043e86e0e659568aede9d0c8273800b3e..main?diff=split

**Comment by folke** [comment] 2021-08-06 07:06
> What does `LspInfo` say? Is sumneko properly connected?
> 
> Could you open a new lua file, add in the below and execute it with `:luafile %`?
> 
> ```lua
>   local ret = {}
>   for _, client in pairs(vim.lsp.get_active_clients()) do
>     ret[client.name] = { root_dir = client.config.root_dir, settings = client.config.settings }
>   end
> print(vim.inspect(ret))
> ```

If anyone can post the result of the above, that would be really helpful.

**Comment by akinsho** [comment] 2021-08-06 07:21
> If I understand correctly, something is broken when you are in a project like ~/projects/foo/lua/bar/init.lua? And you require files there from a vim plugin?

@folke so I have a similar directory setup to this for my local plugins I develop. When I go into those files on my dev machine on the latest commit of `lua-dev` I get completions from compe (which is why I thought things were still working) but I get *zero* diagnostics no, signs, no highlights, *nothing*. The only lsp related functionality that works as far as I could tell was completion.

> If anyone can post the result of the above, that would be really helpful.
I'll post the output of this later on today when I get to my dev machine

**Comment by folke** [comment] 2021-08-06 07:46
I was able to reproduce it after upgrading sumneko. 2.2.3 worked fine, but it's broken in 2.3.2.

My changes between the version of lua-dev that worked and no longer worked were to remove the on_new_config where I previously removed the active root from the library.

This was no longer needed, since it worked without that, but it seems for the latest version of sumneko, this breaks diagnostics.

Will work on a fix.

**Comment by folke** [comment] 2021-08-06 07:54
I just pushed a fix for this. Let me know if you would still experience issues.

**Closed** 2021-08-06 07:53 UTC
Labels: question

**Comment by akinsho** [comment] 2021-08-06 19:16
Seems to be resolved now. Thanks @folke 👍🏿

**Comment by muniter** [comment] 2021-08-06 19:40
I confirm it is resolved, Thanks!!
